/// <reference types="react" />
export declare const P: (props: TextProps) => JSX.Element;
export declare const A: (props: TextProps) => JSX.Element;
export declare const H4: (props: TextProps) => JSX.Element;
export declare const H3: (props: TextProps) => JSX.Element;
export declare const H2: (props: TextProps) => JSX.Element;
export declare const H1: (props: TextProps) => JSX.Element;
export declare const Text: (props: TextProps) => JSX.Element;
//# sourceMappingURL=Text.d.ts.map